<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class FlavorsearchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('flavors')->insert([
            [
                'name' => 'レモン',
                'englishName' => 'Lemon',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'lemon.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'レモンremonfruit',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'オレンジ',
                'englishName' => 'Orange',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'orange.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'orangeオレンジみかん',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'かぼす',
                'englishName' => 'Kabosu',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'kabosu.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'kabosuかぼす',
                'select_type' => 'wired',
                'brand' => '',
            ],
            [
                'name' => 'いちご',
                'englishName' => 'Strawberry',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'storvery.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'いちごichigofruit',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'アーモンド',
                'englishName' => 'almond',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'armondo.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'アーモンド',
                'select_type' => 'wired',
                'brand' => '',
            ],
            [
                'name' => 'カクテル',
                'englishName' => 'Cocktail',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'kakuteru.svg',
                'taste' =>'flesh',
                'category' =>'drink',
                'search_keyword' => 'カクテルkakuteru',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'ミルク',
                'englishName' => 'Milk',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'milk.svg',
                'taste' =>'sweet',
                'category' =>'other',
                'search_keyword' => 'ミルクmilk',
                'select_type' => 'main',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'ピーチ',
                'englishName' => 'Peach',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'piech.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ピーチももpiech',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'ローズ',
                'englishName' => 'Rose',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'rose.svg',
                'taste' =>'flesh',
                'category' =>'spices',
                'search_keyword' => 'roseローズはら',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'ワイン',
                'englishName' => 'Wine',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'wine.svg',
                'taste' =>'flesh',
                'category' =>'drink',
                'search_keyword' => 'wineワイン',
                'select_type' => 'main',
                'brand' => '',
            ],
            [
                'name' => 'ダブルアップル',
                'englishName' => 'DoubleApple',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'DoubleApple.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ダブルアップルDoubleApple',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'ミント',
                'englishName' => 'Mint',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Mint.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ミントMint',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'グァバ',
                'englishName' => 'Guava',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Guava.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'グァバGuava',
                'select_type' => 'wired',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'グレープ',
                'englishName' => 'Grape',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Grape.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'グレープGrape',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'カルダモン',
                'englishName' => 'Cardamom',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Cardamom.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'カルダモンCardamom',
                'select_type' => 'wired',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'ココナッツ',
                'englishName' => 'Coconut',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Coconut.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'ココナッツCoconut',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'エナジードリンク',
                'englishName' => 'Energy drink',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Energydrink.svg',
                'taste' =>'flesh',
                'category' =>'drink',
                'search_keyword' => 'エナジードリンクEnergydrink',
                'select_type' => 'wired',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'キウイ',
                'englishName' => 'Kiwi',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Kiwi.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'キウイKiwi',
                'select_type' => 'wired',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'スイカ',
                'englishName' => 'Water melon',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Watermelon.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'スイカWatermelon',
                'select_type' => 'wired',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'メロン',
                'englishName' => 'Melon',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Melon.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'メロンMelon',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'チェリー',
                'englishName' => 'Cherry',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Cherry.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'チェリーCherry',
                'select_type' => 'main',
                'brand' => 'AlFakhel',
            ],
            [
                'name' => 'ブルーベリーマフィン',
                'englishName' => 'Blueberry muffin',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Blueberrymuffin.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ブルーベリーマフィンBlueberry muffin',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'リモンチェッロ',
                'englishName' => 'Limoncello',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Limoncello.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'リモンチェッロLimoncello',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'ホワイトグミベア',
                'englishName' => 'White gummi bear',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Whitegummibear.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'ホワイトグミベアWhitegummibear',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'モヒートモジョ',
                'englishName' => 'Mojito mojo',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Mojitomojo.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'モヒートモジョMojitomojo',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'ホワイトピーチ',
                'englishName' => 'White peach',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Whitepeach.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'ホワイトピーチWhitepeach',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'シトラスティー',
                'englishName' => 'Citrus tea',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Citrustea.svg',
                'taste' =>'flesh',
                'category' =>'drink',
                'search_keyword' => 'シトラスティーCitrustea',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'マンダリンゼスト',
                'englishName' => 'Mandarin zest',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Mandarinzest.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'マンダリンゼストMandarinzest',
                'select_type' => 'wired',
                'brand' => 'Fumari',
            ],
            [
                'name' => 'ジャパニーズゆず',
                'englishName' => 'Japanese yuzu',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Japaneseyuzu.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ジャパニーズゆずJapaneseyuzu',
                'select_type' => 'main',
                'brand' => 'Social smoke',
            ],
            [
                'name' => '香港ミルクティー',
                'englishName' => 'Hong Kong milk tea',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'HongKongmilktea.svg',
                'taste' =>'sweet',
                'category' =>'drink',
                'search_keyword' => '香港ミルクティーHongKongmilktea',
                'select_type' => 'main',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'G.D.A',
                'englishName' => 'Golden delicious apple',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'GDA.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ゴールデンデリシャスアップルGDA',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'ペアチル',
                'englishName' => 'Pear chill',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Pearchill.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'ペアチルPearchill',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'ドゥルセデレチェ',
                'englishName' => 'Dulche de leche',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Dulchedeleche.svg',
                'taste' =>'hot',
                'category' =>'none',
                'search_keyword' => 'ドゥルセデレチェDulche deleche',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'レモンドロップ',
                'englishName' => 'Lemon drop',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Lemondrop.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'レモンドロップLemondropdeleche',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'シナモンロール',
                'englishName' => 'Cinnamon roll',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Cinnamonroll.svg',
                'taste' =>'flesh',
                'category' =>'spices',
                'search_keyword' => 'シナモンロールCinnamonroll',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'ベリーパンチ',
                'englishName' => 'Berry punch',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Berrypunch.svg',
                'taste' =>'hot',
                'category' =>'none',
                'search_keyword' => 'ベリーパンチBerrypunch',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'ピスタチオブリーズ',
                'englishName' => 'Pistachio Breeze',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'PistachioBreeze.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'ピスタチオブリーズPistachioBreeze',
                'select_type' => 'wired',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'チャイラテ',
                'englishName' => 'Chai latte',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Chailatte.svg',
                'taste' =>'sweet',
                'category' =>'drink',
                'search_keyword' => 'チャイラテChailatte',
                'select_type' => 'main',
                'brand' => 'Social smoke',
            ],
            [
                'name' => 'メロン',
                'englishName' => 'Melon',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Melon.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'メロンMelon',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'バナナ',
                'englishName' => 'Banana',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Banana.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'バナナBanana',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'ホワイトグレープ',
                'englishName' => 'White grape',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Whitegrape.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ホワイトグレープWhitegrape',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'グァバ',
                'englishName' => 'Guava',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Guava.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'グァバGuava',
                'select_type' => 'wired',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'レモン',
                'englishName' => 'Lemon',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Lemon.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'レモンLemon',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'グリーンアップル',
                'englishName' => 'Green apple',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Greenapple.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'グリーンアップルGreenapple',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'ピーチ',
                'englishName' => 'Peach',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Peach.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'ピーチPeach',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'パイナップル',
                'englishName' => 'Pineapple',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Pineapple.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'パイナップルPineapple',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'ペアー',
                'englishName' => 'Pear',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Pear.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'ペアーPear',
                'select_type' => 'wired',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'ストロベリー',
                'englishName' => 'Strawberry',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Strawberry.svg',
                'taste' =>'sweet',
                'category' =>'fruit',
                'search_keyword' => 'ストロベリーStrawberry',
                'select_type' => 'main',
                'brand' => 'De cloud',
            ],
            [
                'name' => 'トワイスジアイス',
                'englishName' => 'Twice the ice',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Twicetheice.svg',
                'taste' =>'hot',
                'category' =>'none',
                'search_keyword' => 'トワイスジアイスTwicetheice',
                'select_type' => 'wired',
                'brand' => 'Trifecta',
            ],
            [
                'name' => 'マウンテンフォグ',
                'englishName' => 'Mountain fog',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Mountainfog.svg',
                'taste' =>'hot',
                'category' =>'none',
                'search_keyword' => 'マウンテンフォグMountainfog',
                'select_type' => 'wired',
                'brand' => 'Trifecta',
            ],
            [
                'name' => 'ペパーミントシェイク',
                'englishName' => 'Peppermint shake',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Peppermintshake.svg',
                'taste' =>'flesh',
                'category' =>'spices',
                'search_keyword' => 'ペパーミントシェイクPeppermintshake',
                'select_type' => 'wired',
                'brand' => 'Trifecta',
            ],
            [
                'name' => 'パイナップルグァバ',
                'englishName' => 'Pineapple guava',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Pineappleguava.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'パイナップルグァバPineappleguava',
                'select_type' => 'wired',
                'brand' => 'Trifecta',
            ],
            [
                'name' => 'タイガ',
                'englishName' => 'Taiga',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Taiga.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'タイガTaiga',
                'select_type' => 'main',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'レモングラス',
                'englishName' => 'Lemon grass',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Lemongrass.svg',
                'taste' =>'flesh',
                'category' =>'spices',
                'search_keyword' => 'レモングラスLemongrass',
                'select_type' => 'main',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'ピーナッツ',
                'englishName' => 'Peanuts',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Peanuts.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'ピーナッツPeanuts',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'ピーナッツ',
                'englishName' => 'Peanuts',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Peanuts.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'ピーナッツPeanuts',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'グレープフルーツ',
                'englishName' => 'Grapefruit',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Grapefruit.svg',
                'taste' =>'flesh',
                'category' =>'fruit',
                'search_keyword' => 'グレープフルーツGrapefruit',
                'select_type' => 'main',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'バジル',
                'englishName' => 'Basil',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Basil.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'バジルBasil',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'バニラアイス',
                'englishName' => 'Vanilla ice cream',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Vanillaicecream.svg',
                'taste' =>'sweet',
                'category' =>'other',
                'search_keyword' => 'バニラアイスVanillaicecream',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'アイス',
                'englishName' => 'Ice',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Ice.svg',
                'taste' =>'flesh',
                'category' =>'other',
                'search_keyword' => 'アイスIce',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'カラクティー',
                'englishName' => 'Karak tea',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Karaktea.svg',
                'taste' =>'hot',
                'category' =>'drink',
                'search_keyword' => 'カラクティーKaraktea',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'チョコレートミント',
                'englishName' => 'Chocolate mint',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Chocolatemint.svg',
                'taste' =>'sweet',
                'category' =>'other',
                'search_keyword' => 'チョコレートミントChocolatemint',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'オリエンタルスパイス',
                'englishName' => 'Oriental spices',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Orientalspices.svg',
                'taste' =>'hot',
                'category' =>'spices',
                'search_keyword' => 'オリエンタルスパイスOrientalspices',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'シナモンクッキー',
                'englishName' => 'Cinnamon cookie',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Cinnamoncookie.svg',
                'taste' =>'sweet',
                'category' =>'other',
                'search_keyword' => 'シナモンクッキーCinnamoncookie',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'バブルガム',
                'englishName' => 'Bubble gum',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Bubblegum.svg',
                'taste' =>'flesh',
                'category' =>'other',
                'search_keyword' => 'バブルガムBubblegum',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'ピザ',
                'englishName' => 'Pizza',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Pizza.svg',
                'taste' =>'hot',
                'category' =>'other',
                'search_keyword' => 'ピザPizza',
                'select_type' => 'wired',
                'brand' => 'Buta tobacco',
            ],
            [
                'name' => 'ブルーヘブン',
                'englishName' => 'Blue heaven',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Blueheaven.svg',
                'taste' =>'flesh',
                'category' =>'other',
                'search_keyword' => 'ブルーヘブンBlueheaven',
                'select_type' => 'wired',
                'brand' => 'Golden lavalina',
            ],
            [
                'name' => 'キーライム',
                'englishName' => 'Key lime',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Keylime.svg',
                'taste' =>'flesh',
                'category' =>'other',
                'search_keyword' => 'キーライムKeylime',
                'select_type' => 'wired',
                'brand' => 'Golden lavalina',
            ],
            [
                'name' => 'ローズガーデン',
                'englishName' => 'Rose garden',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Rosegarden.png',
                'taste' =>'flesh',
                'category' =>'spices',
                'search_keyword' => 'ローズガーデンRosegarden ',
                'select_type' => 'wired',
                'brand' => 'Golden lavalina',
            ],
            [
                'name' => 'コニャック',
                'englishName' => 'Cognac',
                'feature_intro' => '説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明説明',
                'image_id' => 'Cognac.svg',
                'taste' =>'flesh',
                'category' =>'none',
                'search_keyword' => 'コニャックCognac',
                'select_type' => 'wired',
                'brand' => 'Golden lavalina',
            ],
        ]);
    }
}
